import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <ul>
      <Link href={"/products"}><li>Products</li></Link>
      </ul>
      <ul>
      <Link href={"/users"}><li>Users</li></Link>
      </ul>

      <ul>
      <Link href={"/posts"}><li>Posts</li></Link>
      </ul>    </div>
      
    </>
  )
}
